name: LeetCode
on:
  # Schedule daily updates at 12.am
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
jobs:
  leetcode-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved
          plugin_leetcode_user: acul4321
